[phases.setup]
nixPkgs = ["nodejs_22", "libreoffice"]

[phases.install]
cmds = ["npm install", "npm install --prefix frontend"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node backend/index.js"
