/**
 * @module services/teaserReading
 * @description Generates a short, persuasive Sinhala "teaser reading" for the
 * free web chart, structured as topic sections (career, marriage, wealth,
 * health, obstacles, timing). Gemini picks which topics are most "triggering"
 * for THIS chart and writes one grounded teaser sentence per chosen topic —
 * the other topics are simply never generated, so there is no hidden/locked
 * content for a curious user to find in the DOM or network response. The FE
 * renders the untouched topics as static locked cards with zero real content.
 *
 * Persona/tone: reuses the same system_prompt configured for the PJ client's
 * real paid horoscope reports (plugin_configs: horoscope_reading), so the
 * teaser sounds like the same astrologer, not a generic AI voice.
 *
 * Cost control: exactly one Gemini call per unique birth chart. The result is
 * cached in astro_cache.teaser_si (same birth_hash as the chart itself), so
 * every repeat view/refresh of the same chart costs zero additional AI calls.
 */

'use strict';

const db = require('../db');
const { pool, db: sqliteDb, IS_PG } = require('../db/connection');
const { genAI } = require('./gemini');

// Fixed topic catalogue — labels/icons are ours, never generated by the model.
// Gemini only ever chooses a SUBSET of these ids; unchosen ones get no content
// at all (rendered client-side as static locked cards).
const TOPICS = ['career', 'marriage', 'wealth', 'health', 'obstacles', 'timing'];

// Western sign name (as returned by freeastroapi) → Sinhala rashi name.
const RASHI_SI_BY_WESTERN = {
  Aries: 'මේෂ', Taurus: 'වෘෂභ', Gemini: 'මිථුන', Cancer: 'කටක',
  Leo: 'සිංහ', Virgo: 'කන්‍යා', Libra: 'තුලා', Scorpio: 'වෘශ්චික',
  Sagittarius: 'ධනු', Capricorn: 'මකර', Aquarius: 'කුම්භ', Pisces: 'මීන',
};

const PLANET_SI = {
  Sun: 'සූර්ය', Moon: 'චන්ද්‍ර', Mars: 'කුජ', Mercury: 'බුධ', Jupiter: 'ගුරු',
  Venus: 'ශුක්‍ර', Saturn: 'ශනි', Rahu: 'රාහු', Ketu: 'කේතු',
};

const NAKSHATRA_SI = {
  Ashwini: 'අස්විද', Bharani: 'බෙරණ', Krittika: 'කැති', Rohini: 'රෙහෙන',
  Mrigashira: 'මුවසිරස', Ardra: 'අද', Punarvasu: 'පුනාවස', Pushya: 'පුස',
  Ashlesha: 'අස්ලිය', Magha: 'මා', 'Purva Phalguni': 'පුවපල්', 'Uttara Phalguni': 'උත්තරපල්',
  Hasta: 'හත', Chitra: 'සිත', Swati: 'ස්වාති', Vishakha: 'විසා', Anuradha: 'අනුර',
  Jyeshtha: 'දෙට', Mula: 'මුල', 'Purva Ashadha': 'පුවසල', 'Uttara Ashadha': 'උත්තරසල',
  Shravana: 'සවණ', Dhanishtha: 'දෙනට', Shatabhisha: 'සියාවස',
  'Purva Bhadrapada': 'පුවපුටුප', 'Uttara Bhadrapada': 'උත්තරපුටුප', Revati: 'රේවතී',
};

const TEASER_SCHEMA = {
  type: 'object',
  properties: {
    sections: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          topic:  { type: 'string', enum: TOPICS },
          teaser: { type: 'string' },
        },
        required: ['topic', 'teaser'],
      },
    },
  },
  required: ['sections'],
};

async function getCachedTeaser(birthHash) {
  if (IS_PG) {
    const r = await pool.query('SELECT teaser_si FROM astro_cache WHERE birth_hash=$1', [birthHash]);
    return r.rows[0]?.teaser_si || null;
  }
  const row = sqliteDb.prepare('SELECT teaser_si FROM astro_cache WHERE birth_hash=?').get(birthHash);
  return row?.teaser_si || null;
}

async function saveTeaser(birthHash, jsonText) {
  if (IS_PG) {
    await pool.query('UPDATE astro_cache SET teaser_si=$1 WHERE birth_hash=$2', [jsonText, birthHash]);
  } else {
    sqliteDb.prepare('UPDATE astro_cache SET teaser_si=? WHERE birth_hash=?').run(jsonText, birthHash);
  }
}

/** Find today's active Mahadasha/Antardasha lord from the API's vimshottari_dasha object. */
function findCurrentDasha(vimshottariDasha) {
  if (!vimshottariDasha) return null;
  const today = new Date().toISOString().slice(0, 10);
  const entries = Object.values(vimshottariDasha).filter(e => e && e.level === 'Mahadasha');
  const maha = entries.find(e => e.start <= today && today <= e.end);
  if (!maha) return null;
  const antar = (maha.sub_periods || []).find(s => s.start <= today && today <= s.end);
  return { mahadasha: maha.lord, antardasha: antar?.lord || null };
}

/** Simple, deterministic Kuja/Manglik dosha check: Mars in house 1, 4, 7, 8, or 12. */
function checkKujaDosha(marsHouse) {
  return [1, 4, 7, 8, 12].includes(Number(marsHouse));
}

/**
 * Extract a short list of grounded, real facts from the freeastroapi response
 * to hand to Gemini — the model must not invent anything beyond these.
 */
function buildFacts(chartData) {
  const root = chartData?.chart ?? chartData ?? {};
  const asc = root.ascendant ?? {};
  const planets = root.planets ?? [];
  const moon = planets.find(p => p.name === 'Moon');
  const mars = planets.find(p => p.name === 'Mars');
  const dasha = findCurrentDasha(chartData?.vimshottari_dasha);
  const kujaDosha = mars ? checkKujaDosha(mars.house) : false;

  const facts = [];
  if (asc.sign) facts.push(`Lagna (ascendant) rashi: ${RASHI_SI_BY_WESTERN[asc.sign] || asc.sign}`);
  if (moon?.sign) facts.push(`Moon rashi: ${RASHI_SI_BY_WESTERN[moon.sign] || moon.sign}`);
  if (moon?.nakshatra) facts.push(`Moon nakshatra: ${NAKSHATRA_SI[moon.nakshatra] || moon.nakshatra}`);
  if (dasha?.mahadasha) facts.push(`Current Mahadasha lord: ${PLANET_SI[dasha.mahadasha] || dasha.mahadasha}`);
  if (dasha?.antardasha) facts.push(`Current Antardasha lord: ${PLANET_SI[dasha.antardasha] || dasha.antardasha}`);
  if (kujaDosha) facts.push(`Kuja (Mars) dosha is present — Mars is placed in house ${mars.house} from the lagna.`);
  if (chartData?.sade_sati?.active) facts.push(`Sade Sati is currently active (phase: ${chartData.sade_sati.phase || 'unknown'}).`);

  return facts;
}

const TASK_INSTRUCTION = `Above is our astrologer's persona/voice guide used for our real paid reports — adopt the SAME tone, warmth, and cultural voice. Ignore any tool-calling, stage, or conversational instructions in it; you are not having a conversation and have no tools. Your ONLY job right now: read the real chart facts given in the user message, pick the 3 topics (from: career, marriage, wealth, health, obstacles, timing) where these specific facts are most striking/relevant, and write ONE short (1-2 sentence) Sinhala teaser per chosen topic. Rules:
- Reference only the given facts. Never invent a placement, dosha, or dasha not listed.
- Sound personal and specific to this exact chart, not generic astrology.
- Build genuine curiosity or concern — but do NOT explain the full meaning or give any remedy/solution. Stop right at the interesting part.
- Never mention AI, computers, or that this was automatically generated.
- Return ONLY the 3 chosen topics — do not include the other 3 at all.
- Respond using the required JSON schema only.`;

/**
 * Return a cached or freshly-generated teaser reading for this chart.
 * Costs one Gemini call the first time a birth_hash is seen; free after that.
 *
 * @param {Object} chartData - Full freeastroapi response (as returned by calculateVedicChart)
 * @param {string} birthHash - Same hash used by vedicChart's astro_cache row
 * @param {string} clientId  - Client id whose horoscope_reading persona to reuse
 * @returns {Promise<Array<{topic:string, teaser:string}>|null>} Chosen sections, or null
 */
async function generateTeaserReading(chartData, birthHash, clientId) {
  const cached = await getCachedTeaser(birthHash);
  if (cached) {
    try { return JSON.parse(cached).sections || null; } catch { return null; }
  }

  const facts = buildFacts(chartData);
  if (!facts.length) return null;
  if (!process.env.GEMINI_API_KEY) return null;

  try {
    const config = await db.getPluginConfig(clientId, 'horoscope_reading');
    const persona = config?.system_prompt || '';
    const systemInstruction = [persona, TASK_INSTRUCTION].filter(Boolean).join('\n\n');

    const prompt = `Real facts from this customer's chart:\n${facts.map(f => `- ${f}`).join('\n')}`;

    const model = genAI.getGenerativeModel({
      model: 'gemini-2.5-flash',
      systemInstruction,
      generationConfig: {
        temperature: 0.7,
        responseMimeType: 'application/json',
        responseSchema: TEASER_SCHEMA,
      },
    });
    const result = await model.generateContent(prompt);
    const parsed = JSON.parse(result.response.text());

    // Defensive filter: only keep known topics with non-empty text.
    const sections = (parsed.sections || [])
      .filter(s => TOPICS.includes(s.topic) && typeof s.teaser === 'string' && s.teaser.trim())
      .slice(0, 3);

    if (!sections.length) return null;
    await saveTeaser(birthHash, JSON.stringify({ sections }));
    return sections;
  } catch (e) {
    console.error('[TEASER]', e.message);
    return null;
  }
}

module.exports = { generateTeaserReading, TOPICS };
