/**
 * @module services/teaserReading
 * @description Generates a short Sinhala "teaser reading" for the free web
 * chart, structured as topic sections (career, marriage, wealth, health,
 * obstacles, timing). Gemini picks which topics are most striking for THIS
 * chart and writes one grounded passage per chosen topic — the other topics
 * are simply never generated, so there is no hidden/locked content for a
 * curious user to find in the DOM or network response. The FE renders the
 * untouched topics as static locked cards with zero real content.
 *
 * Framing (deliberate, not our conversational persona): the customer's
 * planetary placements have already been entered into the system; each
 * teaser reads like a short passage matched from classical palm-leaf
 * (puskola potha) astrological texts — an impersonal, book-quotation
 * register — NOT a warm human/AI voice speaking directly to the customer.
 *
 * Cost control: exactly one Gemini call per unique birth chart. The result is
 * cached in astro_cache.teaser_si (same birth_hash as the chart itself), so
 * every repeat view/refresh of the same chart costs zero additional AI calls.
 */

'use strict';

const { GoogleGenerativeAI } = require('@google/generative-ai');
const { pool, db: sqliteDb, IS_PG } = require('../db/connection');
const clientRouter = require('./clientRouter');
const { genAI } = require('./gemini');

// Fixed topic catalogue — labels/icons are ours, never generated by the model.
// Gemini only ever chooses a SUBSET of these ids; unchosen ones get no content
// at all (rendered client-side as static locked cards).
const TOPICS = ['career', 'marriage', 'wealth', 'health', 'obstacles', 'timing'];

// freeastroapi identifies signs by numeric sign_id (1=Aries...12=Pisces), never
// a name string — index 0 here is sign_id 1. (Matches the frontend's
// mapFreeAstro.ts mapping, verified against the live API response shape.)
const RASHI_SI_BY_SIGN_ID = [
  'මේෂ', 'වෘෂභ', 'මිථුන', 'කටක', 'සිංහ', 'කන්‍යා',
  'තුලා', 'වෘශ්චික', 'ධනු', 'මකර', 'කුම්භ', 'මීන',
];
const rashiSiFromSignId = (signId) => RASHI_SI_BY_SIGN_ID[((Number(signId) - 1) % 12 + 12) % 12];

const PLANET_SI = {
  Sun: 'සූර්ය', Moon: 'චන්ද්‍ර', Mars: 'කුජ', Mercury: 'බුධ', Jupiter: 'ගුරු',
  Venus: 'ශුක්‍ර', Saturn: 'ශනි', Rahu: 'රාහු', Ketu: 'කේතු',
};

const NAKSHATRA_SI = {
  Ashwini: 'අස්විද', Bharani: 'බෙරණ', Krittika: 'කැති', Rohini: 'රෙහෙන',
  Mrigashira: 'මුවසිරස', Ardra: 'අද', Punarvasu: 'පුනාවස', Pushya: 'පුස',
  Ashlesha: 'අස්ලිය', Magha: 'මා', 'Purva Phalguni': 'පුවපල්', 'Uttara Phalguni': 'උත්තරපල්',
  Hasta: 'හත', Chitra: 'සිත', Swati: 'ස්වාති', Vishakha: 'විසා', Anuradha: 'අනුර',
  Jyeshtha: 'දෙට', Mula: 'මුල', 'Purva Ashadha': 'පුවසල', 'Uttara Ashadha': 'උත්තරසල',
  Shravana: 'සවණ', Dhanishtha: 'දෙනට', Shatabhisha: 'සියාවස',
  'Purva Bhadrapada': 'පුවපුටුප', 'Uttara Bhadrapada': 'උත්තරපුටුප', Revati: 'රේවතී',
};

const TEASER_SCHEMA = {
  type: 'object',
  properties: {
    sections: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          topic:  { type: 'string', enum: TOPICS },
          teaser: { type: 'string' },
        },
        required: ['topic', 'teaser'],
      },
    },
  },
  required: ['sections'],
};

async function getCachedTeaser(birthHash) {
  if (IS_PG) {
    const r = await pool.query('SELECT teaser_si FROM astro_cache WHERE birth_hash=$1', [birthHash]);
    return r.rows[0]?.teaser_si || null;
  }
  const row = sqliteDb.prepare('SELECT teaser_si FROM astro_cache WHERE birth_hash=?').get(birthHash);
  return row?.teaser_si || null;
}

async function saveTeaser(birthHash, jsonText) {
  if (IS_PG) {
    await pool.query('UPDATE astro_cache SET teaser_si=$1 WHERE birth_hash=$2', [jsonText, birthHash]);
  } else {
    sqliteDb.prepare('UPDATE astro_cache SET teaser_si=? WHERE birth_hash=?').run(jsonText, birthHash);
  }
}

/** Find today's active Mahadasha/Antardasha lord from the API's vimshottari_dasha object. */
function findCurrentDasha(vimshottariDasha) {
  if (!vimshottariDasha) return null;
  const today = new Date().toISOString().slice(0, 10);
  const entries = Object.values(vimshottariDasha).filter(e => e && e.level === 'Mahadasha');
  const maha = entries.find(e => e.start <= today && today <= e.end);
  if (!maha) return null;
  const antar = (maha.sub_periods || []).find(s => s.start <= today && today <= s.end);
  return { mahadasha: maha.lord, antardasha: antar?.lord || null };
}

/** Simple, deterministic Kuja/Manglik dosha check: Mars in house 1, 4, 7, 8, or 12. */
function checkKujaDosha(marsHouse) {
  return [1, 4, 7, 8, 12].includes(Number(marsHouse));
}

/**
 * Extract a short list of grounded, real facts from the freeastroapi response
 * to hand to Gemini — the model must not invent anything beyond these.
 */
function buildFacts(chartData) {
  // v2 freeastroapi nests the base chart under `chart`; v1 (legacy cached
  // orders) returned it flat. Support both. Signs are given as numeric
  // sign_id (never a `.sign` name string) — matches the frontend's
  // mapFreeAstro.ts. Planet names come through as `.name` (e.g. "Moon", "Mars").
  const root = chartData?.chart ?? chartData ?? {};
  const asc = root.ascendant ?? {};
  const planets = root.planets ?? [];
  const moon = planets.find(p => p.name === 'Moon');
  const mars = planets.find(p => p.name === 'Mars');
  const dasha = findCurrentDasha(chartData?.vimshottari_dasha ?? root.vimshottari_dasha);
  const kujaDosha = mars ? checkKujaDosha(mars.house) : false;
  const moonNakshatra = typeof moon?.nakshatra === 'string' ? moon.nakshatra : moon?.nakshatra?.name;

  // The ascendant doesn't always carry sign_id in the real API response —
  // only `degree` is guaranteed present — so derive it the same defensive
  // way mapFreeAstro.ts does on the frontend, instead of skipping the fact.
  const ascSignId = asc.sign_id != null
    ? Number(asc.sign_id)
    : (asc.degree != null ? Math.floor((((Number(asc.degree) % 360) + 360) % 360) / 30) + 1 : null);

  const facts = [];
  if (ascSignId != null) facts.push(`Lagna (ascendant) rashi: ${rashiSiFromSignId(ascSignId)}`);
  if (moon?.sign_id != null) facts.push(`Moon rashi: ${rashiSiFromSignId(moon.sign_id)}`);
  if (moonNakshatra) facts.push(`Moon nakshatra: ${NAKSHATRA_SI[moonNakshatra] || moonNakshatra}`);
  if (dasha?.mahadasha) facts.push(`Current Mahadasha lord: ${PLANET_SI[dasha.mahadasha] || dasha.mahadasha}`);
  if (dasha?.antardasha) facts.push(`Current Antardasha lord: ${PLANET_SI[dasha.antardasha] || dasha.antardasha}`);
  if (kujaDosha) facts.push(`Kuja (Mars) dosha is present — Mars is placed in house ${mars.house} from the lagna.`);
  const sadeSati = chartData?.sade_sati ?? root.sade_sati;
  if (sadeSati?.active) facts.push(`Sade Sati is currently active (phase: ${sadeSati.phase || 'unknown'}).`);

  return facts;
}

const SYSTEM_INSTRUCTION = `You are the internal reading-matcher module of a Sri Lankan Vedic astrology system.

FRAMING (critical — follow exactly): The customer's exact planetary placements (graha positions) have ALREADY been entered into the system by our team. Your job is to retrieve/match short passages recorded in classical Sri Lankan palm-leaf manuscripts (puskola potha) and traditional astrological texts that correspond to those placements. You are NOT a human astrologer personally writing to the customer, and you are NOT a friendly AI assistant chatting with them. You are presenting a quick, impersonal system-matched excerpt, as if quoting an old text.

Voice and register:
- Write in a formal, matter-of-fact, slightly archaic Sinhala register — third-person / impersonal, the way a classical text states a finding. Examples of the right register: "...ස්ථානයේ ග්‍රහයාගේ පිහිටීම නිසා ... බව සඳහන් වේ", "... බව පුස්කොළ පොතේ දැක්වේ", "... බව සටහන් වී ඇත".
- Do NOT use warm first-person chat phrasing like "ඔබ දැනගන්න ඕනේ", "මම ඔබට කියන්නම්", or any greeting. This is not a conversation.
- Never mention AI, Gemini, computers, or that this was automatically generated. Never break the "matched from the texts" framing.

Content rules:
- Reference ONLY the real facts given in the user message. Never invent a placement, dosha, or dasha not listed.
- Each teaser: 1-2 sentences, specific to the given facts, not generic astrology filler.
- Build genuine curiosity or mild concern, but do NOT explain the full meaning or give any remedy/solution — stop right at the interesting/concerning point, as if the book excerpt was cut short.

Task: from the six topics (career, marriage, wealth, health, obstacles, timing), choose the 3 where the given facts are most striking, and write one such passage for each. Return ONLY those 3 topics — never mention or hint at the other 3. Respond using the required JSON schema only.`;

/**
 * Resolve which Gemini client/key to use for a client: its own DB-configured
 * key if set, the system env key if it opted into that, otherwise fall back
 * to the system env key anyway (same resolution order as gemini.js).
 */
function resolveGenAI(client) {
  const apiKey = client?.gemini_api_key
    || (client?.use_system_gemini_key ? process.env.GEMINI_API_KEY : null)
    || process.env.GEMINI_API_KEY;
  if (!apiKey) return null;
  return apiKey !== process.env.GEMINI_API_KEY ? new GoogleGenerativeAI(apiKey) : genAI;
}

/**
 * Return a cached or freshly-generated teaser reading for this chart.
 * Costs one Gemini call the first time a birth_hash is seen; free after that.
 *
 * @param {Object} chartData - Full freeastroapi response (as returned by calculateVedicChart)
 * @param {string} birthHash - Same hash used by vedicChart's astro_cache row
 * @param {string} clientId  - Client id whose configured Gemini key to use (e.g. 'astrology_001')
 * @returns {Promise<Array<{topic:string, teaser:string}>|null>} Chosen sections, or null
 */
async function generateTeaserReading(chartData, birthHash, clientId) {
  const cached = await getCachedTeaser(birthHash);
  if (cached) {
    try { return JSON.parse(cached).sections || null; } catch { return null; }
  }

  const facts = buildFacts(chartData);
  if (!facts.length) return null;

  try {
    const client = clientId ? await clientRouter.getClientById(clientId) : null;
    const clientAI = resolveGenAI(client);
    if (!clientAI) return null;

    const prompt = `Real facts from this customer's chart:\n${facts.map(f => `- ${f}`).join('\n')}`;

    const model = clientAI.getGenerativeModel({
      model: 'gemini-2.5-flash',
      systemInstruction: SYSTEM_INSTRUCTION,
      generationConfig: {
        temperature: 0.7,
        responseMimeType: 'application/json',
        responseSchema: TEASER_SCHEMA,
      },
    });
    const result = await model.generateContent(prompt);
    const parsed = JSON.parse(result.response.text());

    // Defensive filter: only keep known topics with non-empty text.
    const sections = (parsed.sections || [])
      .filter(s => TOPICS.includes(s.topic) && typeof s.teaser === 'string' && s.teaser.trim())
      .slice(0, 3);

    if (!sections.length) return null;
    await saveTeaser(birthHash, JSON.stringify({ sections }));
    return sections;
  } catch (e) {
    console.error('[TEASER]', e.message);
    return null;
  }
}

module.exports = { generateTeaserReading, TOPICS };
